#+ summary: "Retrieves all RO-Crates as products according to SKG-IF"
#+ description: "Retrieves all products according to SKG-IF. NOTE: make sure response content type is application/json"
#+ endpoint: "https://rohub2020-api-virtuoso-route-rohub2020.apps.paas.psnc.pl/sparql"
#+ endpoint_in_url: False
#+ method: GET
#+ transform: {
#+      "entity_type": "product",
#+      "local_identifier": "?ro_pid"
#+ }

PREFIX dct:<http://purl.org/dc/terms/>
PREFIX ro:<http://purl.org/wf4ever/ro#>

select ?ro_pid ?ro_id ?ro_title ?ro_desc where {
   ?ro_pid a ro:ResearchObject ; 
      dct:title ?ro_title ;
      dct:description ?ro_desc .
   BIND (CONCAT("ro-id/",REPLACE(STR(?ro_pid), "^.*/([^/]*)$", "$1")) as ?ro_id)
}