#+ summary: "Retrieves all RO-Crates as products according to SKG-IF"
#+ description: "Retrieves all products according to SKG-IF. NOTE: make sure response content type is application/json"
#+ endpoint: "https://rohub2020-api-virtuoso-route-rohub.apps.paas-dev.psnc.pl/sparql"
#+ endpoint_in_url: False
#+ limit: 100
#+ offset: 0
#+ method: GET
#+ transform: {
#+   "@context": [
#+      "https://w3id.org/skg-if/context/skg-if.json",
#+      {
#+        "@base": "https://w3id.org/skg-if/sandbox/oc/",
#+        "skg": "https://w3id.org/skg-if/sandbox/oc/",
#+        "ro" : "http://purl.org/wf4ever/wf4ever#",
#+        "rocrate_researchObject": "http://purl.org/wf4ever/wf4ever#ResearchObject",
#+        "rocrate_copyright-owner": "http://purl.org/spar/pro/copyright-owner",
#+        "rocrate_hasPart": "http://schema.org/hasPart",
#+        "rocrate_email": "http://schema.org/email",
#+        "rocrate_w3id": "skg:w3id"
#+      }
#+   ],
#+   "@graph": [
#+   {
#+      "entity_type": "product",
#+      "local_identifier": "?ro_pid",
#+      "identifiers": [
#+      {
#+          "scheme": "rocrate_w3id",
#+          "value": "?ro_id"
#+      }
#+      ],
#+      "product_type": ["research data","rocrate_researchObject"],
#+      "titles": {
#+          "none": "?ro_title"
#+      },
#+      "abstracts":{
#+          "none": "?ro_desc"
#+      },
#+   }]
#+ }
PREFIX dct:<http://purl.org/dc/terms/>
PREFIX ro:<http://purl.org/wf4ever/ro#>
select ?ro_pid ?ro_id ?ro_title ?ro_desc where {
   ?ro_pid a ro:ResearchObject ; 
      dct:title ?ro_title ;
      dct:description ?ro_desc .
   BIND (CONCAT("ro-id/",REPLACE(STR(?ro_pid), "^.*/([^/]*)$", "$1")) as ?ro_id)
}